---
sidebar: sidebar 
permalink: custom-architectures-plan-file-system.html 
keywords: BeeGFS on NetApp, NetApp Custom Architectures, EF600 
summary: 在建置Ansible庫存之前、請先規劃檔案系統部署。 
---
= 規劃檔案系統
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在建置Ansible庫存之前、請先規劃檔案系統部署。



== 總覽

在部署檔案系統之前、您應該先定義叢集中執行的所有檔案節點、區塊節點和BeeGFS服務需要哪些IP位址、連接埠和其他組態。雖然確切的組態會因叢集的架構而有所不同、但本節定義了一般適用的最佳實務做法和步驟。



== 步驟

. 如果您使用IP型儲存傳輸協定（例如iSER、iSCSI、NVMe/IB或NVMe/RoCE）來將檔案節點連接至區塊節點、請填寫每個建置區塊的下列工作表。單一建置區塊中的每個直接連線都應該有唯一的子網路、而且不應與用於用戶端伺服器連線的子網路重疊。
+
|===


| 檔案節點 | IB連接埠 | IP 位址 | 區塊節點 | IB連接埠 | 實體IP | 虛擬IP（僅適用於配備HDRIB的EF600） 


| <HOSTNAME> | <PORT> | <IP/SUBNET> | <HOSTNAME> | <PORT> | <IP/SUBNET> | <IP/SUBNET> 
|===
+

NOTE: 如果每個建置區塊中的檔案和區塊節點是直接連線的、您通常可以針對多個建置區塊重複使用相同的IP/配置。

. 無論您是使用InfiniBand或RDMA over Converged Ethernet（RoCE）進行儲存網路、請填寫下列工作表、以判斷將用於HA叢集服務、BeeGFS檔案服務和用戶端進行通訊的IP範圍：
+
|===
| 目的 | InfiniBand連接埠 | IP位址或範圍 


| BeeGFS叢集IP | <INTERFACE(s)> | <RANGE> 


| BeeGFS管理 | <INTERFACE(s)> | <IP(s)> 


| BeeGFS中繼資料 | <INTERFACE(s)> | <RANGE> 


| BeeGFS儲存設備 | <INTERFACE(s)> | <RANGE> 


| BeeGFS用戶端 | <INTERFACE(s)> | <RANGE> 
|===
+
.. 如果您使用單一IP子網路、則只需要一張工作表、否則請填寫第二個子網路的工作表。


. 根據上述資訊、針對叢集中的每個建置區塊、填寫下列工作表、以定義BeeGFS將執行哪些服務。針對每項服務、指定偏好的/次要檔案節點、網路連接埠、浮動IP、NUMA區域指派（若有需要）、以及將用於其目標的區塊節點。填寫工作表時、請參閱下列準則：
+
.. 也請將BeeGFS服務指定為兩者 `mgmt.yml`、 `meta_<ID>.yml`或 `storage_<ID>.yml` 其中ID代表此檔案系統中該類型所有BeeGFS服務的唯一編號。此慣例將簡化後續各節中的工作表參照、同時建立檔案以設定每項服務。
.. BeeGFS服務的連接埠只需在特定的建置區塊中具有唯一性。請確保具有相同連接埠號碼的服務無法在同一個檔案節點上執行、以避免連接埠衝突。
.. 必要時、服務可以使用來自多個區塊節點和（或）儲存資源池的磁碟區（並非所有磁碟區都必須由同一個控制器擁有）。多個服務也可以共用相同的區塊節點和/或儲存資源池組態（個別磁碟區將在稍後的章節中定義）。
+
|===
| BeeGFS服務（檔案名稱） | 檔案節點 | 連接埠 | 浮動IP | NUMA區域 | 區塊節點 | 儲存資源池 | 擁有控制器 


| _setx.yml <ID> <SERVICE TYPE> | <PREFERRED FILE NODE> <SECONDARY FILE NODE(s)> | <PORT> | 部分：功能<IP/SUBNET> <IP/SUBNET> <INTERFACE> <INTERFACE> | <NUMA NODE/ZONE> | <BLOCK NODE> | <STORAGE POOL/VOLUME GROUP> | <A OR B> 
|===




如需標準慣例、最佳實務做法及填寫範例工作表的詳細資訊、請參閱 link:beegfs-deploy-bestpractice.html["最佳實務做法"^] 和 link:beegfs-deploy-define-inventory.html["定義BeeGFS建置區塊"^] BeeGFS中有關NetApp認證架構的章節。
