---
settings:
  name: BeeGFS on NetApp with E-Series Storage
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: zh-tw,us-en,ja-jp,ko-kr,zh-cn,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: NetApp文件上的BeeGFS
    url: "/index.html"
  - title: 開始使用
    entries:
    - title: 本網站內容
      url: "/whats-included.html"
    - title: 詞彙與概念
      url: "/beegfs-terms.html"
  - title: 使用通過驗證的架構
    entries:
    - title: 總覽與需求
      entries:
      - title: 解決方案總覽
        url: "/beegfs-solution-overview.html"
      - title: 設計世代
        url: "/beegfs-gens.html"
      - title: 架構總覽
        url: "/beegfs-architecture-overview.html"
      - title: 技術需求
        url: "/beegfs-technology-requirements.html"
    - title: 檢視解決方案設計
      entries:
      - title: 設計總覽
        url: "/beegfs-design-overview.html"
      - title: 硬體組態
        url: "/beegfs-design-hardware-architecture.html"
      - title: 軟體組態
        url: "/beegfs-design-software-architecture.html"
      - title: 設計驗證
        url: "/beegfs-design-solution-verification.html"
      - title: 規模調整準則
        url: "/beegfs-design-solution-sizing-guidelines.html"
      - title: 效能調校
        url: "/beegfs-design-performance-tuning.html"
      - title: 大容量選項
        url: "/beegfs-design-high-capacity-building-block.html"
    - title: 部署解決方案
      entries:
      - title: 部署總覽
        url: "/beegfs-deploy-overview.html"
      - title: 瞭解Ansible庫存
        url: "/beegfs-deploy-learn-ansible.html"
      - title: 檢視最佳實務做法
        url: "/beegfs-deploy-bestpractice.html"
      - title: 部署硬體
        url: "/beegfs-deploy-hardware.html"
      - title: 部署軟體
        entries:
        - title: 設定檔案和區塊節點
          url: "/beegfs-deploy-setup-nodes.html"
        - title: 調整系統設定以獲得效能
          url: beegfs-deploy-file-node-tuning.html
        - title: 設定Ansible控制節點
          url: "/beegfs-deploy-setting-up-an-ansible-control-node.html"
        - title: 建立可Ansible庫存
          url: "/beegfs-deploy-create-inventory.html"
        - title: 定義BeeGFS建置區塊
          url: "/beegfs-deploy-define-inventory.html"
        - title: 部署BeeGFS
          url: "/beegfs-deploy-playbook.html"
        - title: 設定BeeGFS用戶端
          url: "/beegfs-deploy-configure-clients.html"
      - title: 擴充BeeGFS叢集
        url: "/beegfs-deploy-scale-building-blocks.html"
      - title: 建議的Volume百分比
        url: "/beegfs-deploy-recommended-volume-percentages.html"
      - title: 大容量選項
        url: "/beegfs-deploy-high-capacity-building-block.html"
  - title: 使用自訂架構
    entries:
    - title: 總覽與需求
      url: "/custom-architectures-overview.html"
    - title: 初始設定
      entries:
      - title: 安裝和連接硬體
        url: "/custom-architectures-setup-cable-hw.html"
      - title: 設定檔案和區塊節點
        url: "/custom-architectures-setup-nodes.html"
      - title: 設定Ansible控制節點
        url: "/custom-architectures-setup-ansible-control-node.html"
    - title: 定義BeeGFS檔案系統
      entries:
      - title: Ansible Inventory Overview
        url: "/custom-architectures-inventory-overview.html"
      - title: 規劃檔案系統
        url: "/custom-architectures-plan-file-system.html"
      - title: 定義檔案和區塊節點
        entries:
        - title: 設定個別檔案節點
          url: "/custom-architectures-inventory-configure-file-nodes.html"
        - title: 設定個別區塊節點
          url: "/custom-architectures-inventory-configure-block-nodes.html"
        - title: 指定通用檔案節點組態
          url: "/custom-architectures-inventory-common-file-node-configuration.html"
        - title: 指定通用區塊節點組態
          url: "/custom-architectures-inventory-common-block-node-configuration.html"
      - title: 定義BeeGFS服務
        entries:
        - title: BeeGFS管理服務
          url: "/custom-architectures-inventory-beegfs-management.html"
        - title: BeeGFS中繼資料服務
          url: "/custom-architectures-inventory-beegfs-metadata.html"
        - title: BeeGFS儲存服務
          url: "/custom-architectures-inventory-beegfs-storage.html"
      - title: 將BeeGFS服務對應至檔案節點
        url: "/custom-architectures-inventory-map-services-to-file-nodes.html"
    - title: 部署BeeGFS檔案系統
      entries:
      - title: Ansible教戰手冊總覽
        url: "/custom-architectures-deploy-playbook-overview.html"
      - title: 部署BeeGFS HA叢集
        url: "/custom-architectures-deploy-ha-cluster.html"
      - title: 部署BeeGFS用戶端
        url: "/custom-architectures-deploy-beegfs-clients.html"
      - title: 驗證BeeGFS部署
        url: "/custom-architectures-deploy-verify.html"
  - title: 管理BeeGFS叢集
    entries:
    - title: 概述、主要概念和術語
      url: "/administer-clusters-overview.html"
    - title: 使用Ansible與PCS的時機
      url: "/administer-clusters-ansible-pcs.html"
    - title: 檢查叢集的狀態
      url: "/administer-clusters-examine-state.html"
    - title: 重新設定及更新
      entries:
      - title: 重新設定HA叢集和BeeGFS
        url: "/administer-clusters-reconfigure.html"
      - title: 更新HA叢集和BeeGFS
        url: "/administer-clusters-update.html"
    - title: 服務與維護
      entries:
      - title: 容錯移轉和容錯回復服務
        url: "/administer-clusters-failover-failback.html"
      - title: 將叢集置於維護模式
        url: "/administer-clusters-maintenance-mode.html"
      - title: 停止並啟動叢集
        url: "/administer-clusters-stop-start-cluster.html"
      - title: 取代檔案節點
        url: "/administer-clusters-replace-file-nodes.html"
      - title: 擴充或縮小叢集
        url: "/administer-clusters-expand-shrink-cluster.html"
    - title: 疑難排解
      url: "/administer-clusters-troubleshoot.html"
  - title: 法律聲明
    url: "/legal-notices.html"
product-family:
  name: E-Series
  repo: e-series-family
