---
sidebar: sidebar 
permalink: second-gen/beegfs-deploy-setup-nodes.html 
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600 
summary: 在每部伺服器的基礎板管理控制器（BMC）上設定網路、並在每個控制器上設定管理連接埠。 
---
= 設定檔案節點和區塊節點
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
雖然大部分的軟體組態工作都是使用NetApp提供的Ansible集合來自動化、但您必須在每部伺服器的底板管理控制器（BMC）上設定網路、並在每個控制器上設定管理連接埠。



== 設定檔案節點

. 在每部伺服器的基礎板管理控制器（BMC）上設定網路。
+
若要瞭解如何為已驗證的 Lenovo SR665 V3 檔案節點設定網路、請參閱 https://pubs.lenovo.com/sr665-v3/["Lenovo ThinkSystem文件"^]。

+

NOTE: 底板管理控制器（BMC）有時稱為服務處理器、是內建於各種伺服器平台的頻外管理功能的一般名稱、即使作業系統未安裝或無法存取、也能提供遠端存取。廠商通常會以自己的品牌行銷這項功能。例如、在Lenovo SR665上、BMC稱為_Lenovo XClarity Controller（XCC）_。

. 設定系統設定以獲得最大效能。
+
您可以使用UEFI設定（先前稱為BIOS）或使用許多BMC提供的Redfish API來設定系統設定。系統設定會因做為檔案節點的伺服器機型而有所不同。

+
若要了解如何配置已驗證的 Lenovo SR665 V3 檔案節點的系統設置，請參閱link:beegfs-deploy-file-node-tuning.html["調整系統設定以獲得效能"] 。

. 安裝 Red Hat Enterprise Linux (RHEL) 9.4 並設定用於管理作業系統的主機名稱和網路端口，包括來自 Ansible 控制節點的 SSH 連線。
+
此時請勿在任何InfiniBand連接埠上設定IP。

+

NOTE: 雖然並非嚴格要求、但後續章節假設主機名稱會依序編號（例如H1-HN）、並提及應該在ODD或偶數主機上完成的工作。

. 使用 Red Hat Subscription Manager 註冊並訂閱系統，以允許從官方 Red Hat 儲存庫安裝所需的軟體包，並將更新限制在支援的 Red Hat 版本上：  `subscription-manager release --set=9.4` 。有關說明，請參閱 https://access.redhat.com/solutions/253273["如何註冊及訂閱RHEL系統"^] 和  https://access.redhat.com/solutions/2761031["如何限制更新"^]。
. 啟用包含高可用度所需套件的Red Hat儲存庫。
+
....
subscription-manager repo-override --repo=rhel-9-for-x86_64-highavailability-rpms --add=enabled:1
....
. 將所有 HCA 韌體更新至使用link:..administer/clusters-update-hca-firmware.html["更新檔案節點介面卡韌體"^]指南中建議的版本link:beegfs-technology-requirements.html["技術需求"]。




== 設定區塊節點

設定每個控制器上的管理連接埠、以設定EF600區塊節點。

. 在每個EF600控制器上設定管理連接埠。
+
有關配置端口的說明，請轉至 https://docs.netapp.com/us-en/e-series/install-hw-ef600/complete-setup-task.html#step-2-connect-and-configure-the-management-connection["E系列文件中心"^]。

. （可選）設定每個系統的儲存陣列名稱。
+
設定名稱可讓您更容易在後續章節中參考每個系統。有關設置陣列名稱的說明，請轉至 https://docs.netapp.com/us-en/e-series-santricity/sm-interface/setup-wizard-overview.html#first-time-setup["E系列文件中心"^]。




NOTE: 雖然並非嚴格要求、但後續主題會假設儲存陣列名稱會依序編號（例如C1 - CN）、並提及應該在ODD或偶數系統上完成的步驟。
