---
sidebar: sidebar 
permalink: beegfs-deploy-setup-nodes.html 
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600 
summary: 在每部伺服器的基礎板管理控制器（BMC）上設定網路、並在每個控制器上設定管理連接埠。 
---
= 設定檔案節點和區塊節點
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
雖然大部分的軟體組態工作都是使用NetApp提供的Ansible集合來自動化、但您必須在每部伺服器的底板管理控制器（BMC）上設定網路、並在每個控制器上設定管理連接埠。



== 設定檔案節點

. 在每部伺服器的基礎板管理控制器（BMC）上設定網路。
+
若要瞭解如何為已驗證的Lenovo SR665檔案節點設定網路、請參閱 https://thinksystem.lenovofiles.com/help/index.jsp?topic=%2F7D2W%2Fset_the_network_connection.html["Lenovo ThinkSystem文件"^]。

+

NOTE: 底板管理控制器（BMC）有時稱為服務處理器、是內建於各種伺服器平台的頻外管理功能的一般名稱、即使作業系統未安裝或無法存取、也能提供遠端存取。廠商通常會以自己的品牌行銷這項功能。例如、在Lenovo SR665上、BMC稱為_Lenovo XClarity Controller（XCC）_。

. 設定系統設定以獲得最大效能。
+
您可以使用UEFI設定（先前稱為BIOS）或使用許多BMC提供的Redfish API來設定系統設定。系統設定會因做為檔案節點的伺服器機型而有所不同。

+
若要瞭解如何設定已驗證之Lenovo SR665檔案節點的系統設定、請參閱 link:beegfs-deploy-file-node-tuning.html["調整系統設定以獲得效能"]。

. 安裝Red Hat 8.4並設定用於管理作業系統的主機名稱和網路連接埠、包括從Ansible控制節點進行SSH連線。
+
此時請勿在任何InfiniBand連接埠上設定IP。

+

NOTE: 雖然並非嚴格要求、但後續章節假設主機名稱會依序編號（例如H1-HN）、並提及應該在ODD或偶數主機上完成的工作。

. 使用RedHat訂購管理程式來註冊及訂閱系統、以便從正式的Red Hat儲存庫安裝所需的套件、並將更新限制為支援的Red Hat版本：「Subscree-manager版本--set=8.4」。如需相關指示、請參閱 https://access.redhat.com/solutions/253273["如何註冊及訂閱RHEL系統"^] 和  https://access.redhat.com/solutions/2761031["如何限制更新"^]。
. 啟用包含高可用度所需套件的Red Hat儲存庫。
+
....
subscription-manager repo-override --repo=rhel-8-for-x86_64-highavailability-rpms --add=enabled:1
....
. 將所有ConnectX-6 HCA韌體更新為中建議的版本 link:beegfs-technology-requirements.html["技術需求"]。
+
您可以下載並執行已套用建議韌體的mlxup工具版本、以完成此更新。您可以從下載此工具 https://network.nvidia.com/support/firmware/mlxup-mft/["mlxup -更新與查詢公用程式"^] （link:https://docs.nvidia.com/networking/display/MLXUPFWUTILITY/mlxup+-+Firmware+Utility+User+Guide["使用指南"^]）。





== 設定區塊節點

設定每個控制器上的管理連接埠、以設定EF600區塊節點。

. 在每個EF600控制器上設定管理連接埠。
+
如需設定連接埠的指示、請前往 https://docs.netapp.com/us-en/e-series/maintenance-ef600/hpp-overview-supertask-concept.html["E系列文件中心"^]。

. （可選）設定每個系統的儲存陣列名稱。
+
設定名稱可讓您更容易在後續章節中參考每個系統。如需設定陣列名稱的指示、請前往 https://docs.netapp.com/us-en/e-series/maintenance-ef600/hpp-overview-supertask-concept.html["E系列文件中心"^]。




NOTE: 雖然並非嚴格要求、但後續主題會假設儲存陣列名稱會依序編號（例如C1 - CN）、並提及應該在ODD或偶數系統上完成的步驟。
