---
sidebar: sidebar 
permalink: beegfs-design-solution-sizing-guidelines.html 
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600 
summary: BeeGFS解決方案包含根據驗證測試來調整效能和容量規模的建議。 
---
= 規模調整準則
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BeeGFS解決方案包含根據驗證測試來調整效能和容量規模的建議。

建置區塊架構的目標、是透過新增多個建置區塊來建立易於調整規模的解決方案、以符合特定BeeGFS系統的需求。根據以下準則、您可以預估BeeGFS建置區塊的數量和類型、以符合您環境的需求。

請記住、這些預估是最佳的效能表現。綜合基準測試應用程式是以實際應用程式可能無法使用的方式來撰寫及使用、以最佳化基礎檔案系統的使用。



== 效能規模調整

下表提供建議的效能規模調整。

|===
| 組態設定檔 | 1MiB讀取 | 1MiB寫入 


| 中繼資料+儲存設備 | 62GiBps | 21GiBps 


| 僅儲存設備 | 64GiBps | 21GiBps 
|===
中繼資料容量規模預估是根據「經驗法則」、在BeeGFS中、500 GB的容量足以容納約1.5億個檔案。（如需詳細資訊、請參閱BeeGFS文件 https://doc.beegfs.io/latest/system_design/system_requirements.html["系統需求"^]）

使用存取控制清單等功能、以及每個目錄的目錄和檔案數量、也會影響中繼資料空間的使用速度。儲存容量預估會考慮可用磁碟機容量、以及RAID 6和XFS負荷。



== 中繼資料+儲存建置區塊的容量規模

下表提供中繼資料與儲存建置區塊的建議容量規模調整。

|===
| 磁碟機大小（2+2 RAID 1）中繼資料Volume群組 | 中繼資料容量（檔案數） | 磁碟機大小（8+2 RAID 6）儲存Volume群組 | 儲存容量（檔案內容） 


| 1.92TB | 179712萬 | 1.92TB | 47.91TB 


| 3.84 TB | 3、594、240000 | 3.84 TB | 95.84 TB 


| 7.68TB | 7、557、12、000 | 7.68TB | 201.51TB 


| 15.3TB | 16156,800000 | 15.3TB | 430.84 TB 
|===

NOTE: 調整中繼資料加上儲存建置區塊規模時、您可以使用較小的磁碟機來進行中繼資料磁碟區群組、而非儲存磁碟區群組、藉此降低成本。



== 專為儲存設備建置區塊調整容量

下表針對純儲存建置區塊提供經驗法則容量規模調整。

|===
| 磁碟機大小（8+2 RAID 6）儲存Volume群組 | 儲存容量（檔案內容） 


| 1.92TB | 59.89TB 


| 3.84 TB | 119.80TB 


| 7.68TB | 251.89TB 


| 15.3TB | 538.55TB 
|===

NOTE: 除非啟用全域檔案鎖定、否則在基礎（第一）建置區塊中納入管理服務的效能和容量負荷最小。
