---
sidebar: sidebar 
permalink: beegfs-solution-overview.html 
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600 
summary: BeeGFS on NetApp解決方案結合BeeGFS平行檔案系統與NetApp EF600儲存系統、打造可靠、可擴充且具成本效益的基礎架構、可跟上嚴苛工作負載的腳步。 
---
= 解決方案總覽
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BeeGFS on NetApp解決方案結合BeeGFS平行檔案系統與NetApp EF600儲存系統、打造可靠、可擴充且具成本效益的基礎架構、可跟上嚴苛工作負載的腳步。



== NVA方案

NetApp上的BeeGFS解決方案是NetApp驗證架構（NVA）方案的一部分、可為客戶提供特定工作負載和使用案例的參考組態和規模調整指導。NVA解決方案經過徹底測試與設計、可將部署風險降至最低、並加速上市時間。



== 設計總覽

NetApp 上的 BeeGFS 解決方案是一種可擴充的建置區塊架構、可針對各種嚴苛的工作負載進行設定。無論是處理許多小型檔案、管理大量檔案作業、或是混合式工作負載、都能自訂檔案系統以滿足這些需求。高可用度的設計採用兩層硬體結構、可在多個硬體層進行自動容錯移轉、確保效能一致、即使在部分系統降級期間也是如此。BeeGFS 檔案系統可在不同的 Linux 套裝作業系統中提供高效能且可擴充的環境、並為用戶端提供單一易存取的儲存命名空間。如需詳細資訊，請參閱 link:beegfs-architecture-overview.html["架構總覽"]。



== 使用案例

下列使用案例適用於NetApp上的BeeGFS解決方案：

* NVIDIA DGX SuperPOD 系統採用 DGX 、搭配 A100 、 H100 、 H200 和 B200 GPU 。
* 人工智慧（AI）包括機器學習（ML）、深度學習（DL）、大規模自然語言處理（NLP）、以及自然語言理解（N5U）。如需詳細資訊、請參閱 https://www.netapp.com/blog/beefs-for-ai-fact-vs-fiction/["BeeGFS for AI：事實與虛構"^]。
* 高效能運算（HPC）、包括透過MPI（訊息傳遞介面）和其他分散式運算技術加速的應用程式。如需詳細資訊、請參閱 https://www.netapp.com/blog/beegfs-for-ai-ml-dl/["為什麼BeeGFS超越HPC"^]。
* 應用程式工作負載的特徵為：
+
** 讀取或寫入大於1GB的檔案
** 由多個用戶端（10s、100s和1000s）讀取或寫入同一個檔案


* 多TB或數PB資料集。
* 需要單一儲存命名空間的環境、可針對大型與小型檔案的組合進行最佳化。




== 效益

在NetApp上使用BeeGFS的主要優點包括：

* 通過驗證的硬體設計可提供完整的硬體與軟體元件整合、確保可預測的效能與可靠性。
* 使用Ansible進行部署與管理、以達到簡化與大規模一致的目標。
* 使用E系列效能分析器和BeeGFS外掛程式提供監控和觀察能力。如需詳細資訊、請參閱 https://www.netapp.com/blog/monitoring-netapp-eseries/["介紹監控NetApp E系列解決方案的架構"^]。
* 高可用度採用共享磁碟架構、提供資料持久性與可用度。
* 使用Container和Kubernetes支援現代化的工作負載管理與協調。如需詳細資訊、請參閱 https://www.netapp.com/blog/kubernetes-meet-beegfs/["Kubernetes與BeeGFS會面：這是一段符合未來需求的投資故事"^]。

