---
sidebar: sidebar 
permalink: administer-clusters-expand-shrink-cluster.html 
keywords: BeeGFS on NetApp, HA, Cluster, Administration, replace 
summary: 新增或移除叢集的建置區塊。 
---
= 擴充或縮小叢集
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
新增或移除叢集的建置區塊。



== 總覽

本節說明各種考量事項和選項、以調整BeeGFS HA叢集的大小。一般而言、叢集大小是透過新增或移除建置區塊來調整、而建置區塊通常是以HA配對形式設定兩個檔案節點。如果需要、也可以新增或移除個別的檔案節點（或其他類型的叢集節點）。



== 將建置區塊新增至叢集



=== 考量

透過新增額外的建置區塊來擴充叢集、是一項簡單的程序。開始之前、請記住每個HA叢集中叢集節點的最小和最大數量限制、並決定是否要將節點新增至現有HA叢集、或是建立新的HA叢集。通常每個建置區塊都由兩個檔案節點組成、但每個叢集的節點數最少為三個節點（以建立仲裁）、建議（測試）最多為十個節點。在進階案例中、您可以新增單一「tiebreaker」節點、而在部署雙節點叢集時、該節點不會執行任何BeeGFS服務。如果您正在考慮進行這類部署、請聯絡NetApp支援部門。

在決定如何擴充叢集時、請謹記這些限制和任何預期的未來叢集成長。例如、如果您有六個節點叢集、需要再新增四個節點、建議您只是啟動一個新的HA叢集。


TIP: 請記住、單一BeeGFS檔案系統可由多個獨立的HA叢集組成。如此一來、檔案系統就能繼續擴充、遠遠超過基礎HA叢集元件的建議/硬限制。



=== 步驟

將建置區塊新增至叢集時、您需要建立 `host_vars` 每個新檔案節點和區塊節點（E系列陣列）的檔案。這些主機的名稱需要新增至庫存、以及要建立的新資源。對應的 `group_vars` 需要為每個新資源建立檔案。請參閱 link:custom-architectures-overview.html["使用自訂架構"^] 章節以取得詳細資料。

建立正確的檔案之後、只需要使用以下命令重新執行自動化作業：

[source, console]
----
ansible-playbook -i <inventory>.yml <playbook>.yml
----


== 從叢集移除建置區塊

當您需要淘汰建置區塊時、請謹記下列幾點考量事項：

* 此建置區塊中執行哪些BeeGFS服務？
* 是否只有檔案節點即將淘汰、而且區塊節點應附加至新的檔案節點？
* 如果整個建置區塊都已淘汰、資料是否應該移至新的建置區塊、分散到叢集中的現有節點、或移至新的BeeGFS檔案系統或其他儲存系統？
* 這種情況是否會在停電期間發生、還是應該在不中斷營運的情況下進行？
* 建置區塊是否正在使用中、或主要包含不再使用的資料？


由於可能的起點和所需的終端狀態各不相同、請聯絡NetApp支援部門、以便我們根據您的環境和需求、找出並協助實作最佳策略。
