---
sidebar: sidebar 
permalink: administer-clusters-examine-state.html 
keywords: BeeGFS on NetApp, HA, Cluster, Administration, pcs 
summary: 使用PC檢視叢集的狀態。 
---
= 檢查叢集的狀態
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
使用PC檢視叢集的狀態。



== 總覽

執行中 `pcs status` 從任何叢集節點、都是查看叢集整體狀態及每個資源狀態（例如BeeGFS服務及其相依性）的最簡單方法。本節將說明您在的輸出中所能找到的內容 `pcs status` 命令。



== 瞭解輸出來源 `pcs status`

執行 `pcs status` 在任何叢集服務（起搏器和電暈器同步）啟動的叢集節點上。輸出頂端會顯示叢集摘要：

[source, console]
----
[root@beegfs_01 ~]# pcs status
Cluster name: hacluster
Cluster Summary:
  * Stack: corosync
  * Current DC: beegfs_01 (version 2.0.5-9.el8_4.3-ba59be7122) - partition with quorum
  * Last updated: Fri Jul  1 13:37:18 2022
  * Last change:  Fri Jul  1 13:23:34 2022 by root via cibadmin on beegfs_01
  * 6 nodes configured
  * 235 resource instances configured
----
以下章節列出叢集中的節點：

[source, console]
----
Node List:
  * Node beegfs_06: standby
  * Online: [ beegfs_01 beegfs_02 beegfs_04 beegfs_05 ]
  * OFFLINE: [ beegfs_03 ]
----
這特別代表任何處於待命或離線狀態的節點。待命中的節點仍在參與叢集、但標記為不符合執行資源的資格。離線的節點表示叢集服務未在該節點上執行、可能是因為手動停止、或是因為節點已重新開機/關機。


NOTE: 當節點初次啟動時、叢集服務將會停止、需要手動啟動、以避免意外將資源還原至不正常的節點。

如果節點因為非管理原因（例如故障）而處於待命或離線狀態、則會在節點狀態旁以括弧顯示其他文字。例如、如果隔離功能已停用、而資源遇到您將會看到的故障 `Node <HOSTNAME>: standby (on-fail)`。另一個可能的狀態是 `Node <HOSTNAME>: UNCLEAN (offline)`（這會短暫地被視為節點正在被圍起來、但如果隔離失敗、表示叢集無法確認節點狀態、則會持續存在（這可能會封鎖其他節點上的資源啟動）。

下一節顯示叢集中所有資源及其狀態的清單：

[source, console]
----
Full List of Resources:
  * mgmt-monitor	(ocf::eseries:beegfs-monitor):	 Started beegfs_01
  * Resource Group: mgmt-group:
    * mgmt-FS1	(ocf::eseries:beegfs-target):	 Started beegfs_01
    * mgmt-IP1	(ocf::eseries:beegfs-ipaddr2):	 Started beegfs_01
    * mgmt-IP2	(ocf::eseries:beegfs-ipaddr2):	 Started beegfs_01
    * mgmt-service	(systemd:beegfs-mgmtd):	 Started beegfs_01
[...]
----
與節點類似、如果資源有任何問題、資源狀態旁會顯示其他文字、並以括弧表示。例如、如果心臟起搏器要求資源停止、但無法在分配的時間內完成、則心臟起搏器會嘗試隔離節點。如果禁用隔離功能或隔離操作失敗，則資源狀態將是 `FAILED <HOSTNAME> (blocked)` 而起搏器將無法在不同的節點上啟動。

值得一提的是、BeeGFS HA叢集運用了許多BeeGFS最佳化的自訂OCF資源代理程式。特別是BeeGFS監視器、負責在特定節點上的BeeGFS資源無法使用時觸發容錯移轉。
