---
sidebar: sidebar 
permalink: administer/clusters-reconfigure.html 
keywords: BeeGFS on NetApp, HA, Cluster, Administration, Ansible, pcs 
summary: 使用Ansible重新設定叢集。 
---
= 重新設定HA叢集和BeeGFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
使用Ansible重新設定叢集。



== 總覽

一般而言、只要更新 Ansible 清查並重新執行 `ansible-playbook`命令、即可重新設定 BeeGFS HA 叢集的任何層面。這包括更新警示、變更永久隔離組態或調整BeeGFS服務組態。您 `group_vars/ha_cluster.yml`可以使用檔案來調整這些選項、並在link:../custom/architectures-inventory-common-file-node-configuration.html["指定通用檔案節點組態"^]一節中找到完整的選項清單。

如需管理員在執行維護或服務叢集時應注意的特定組態選項詳細資料、請參閱下方。



== 如何停用和啟用屏障

設定叢集時、預設會啟用/需要隔離功能。在某些情況下、可能需要暫時停用隔離功能、以確保在執行某些維護作業（例如升級作業系統）時、不會意外關閉節點。雖然可以手動停用此功能、但系統管理員仍應注意取捨。



=== 選項1：使用Ansible（建議）停用隔離功能。

使用Ansible停用隔離功能時、BeeGFS監視器的失敗動作會從「Fence」變更為「standby」（待命）。這表示、如果BeeGFS監視器偵測到故障、就會嘗試將節點置於待命狀態、並容錯移轉所有BeeGFS服務。在主動式疑難排解/測試之外、這通常比選項2更為理想。缺點是、如果資源無法在原始節點上停止、就會被封鎖、無法從其他位置啟動（這也是為什麼正式作業叢集通常需要隔離）。

. 在您的Ansible庫存中 `groups_vars/ha_cluster.yml` 新增下列組態：
+
[source, console]
----
beegfs_ha_cluster_crm_config_options:
    stonith-enabled: False
----
. 重新執行「Ansible」方針、將變更套用至叢集。




=== 選項2：手動停用隔離功能。

在某些情況下、您可能想要暫時停用隔離功能、而不重新執行Ansible、或許是為了協助疑難排解或測試叢集。


WARNING: 在此組態中、如果BeeGFS監視器偵測到故障、叢集將嘗試停止對應的資源群組。它不會觸發完整容錯移轉、也不會嘗試重新啟動受影響的資源群組、或將其移至其他主機。若要恢復、請先解決所有問題、然後再執行 `pcs resource cleanup` 或手動將節點置於待命狀態。

步驟：

. 若要判斷隔離（stonith）是否已全域啟用或停用、請執行： `pcs property show stonith-enabled`
. 若要停用隔離執行： `pcs property set stonith-enabled=false`
. 若要啟用隔離執行： `pcs property set stonith-enabled=true`



CAUTION: 下次執行 Ansible 劇本時，此設定將被覆蓋。
