---
sidebar: sidebar 
permalink: custom/architectures-setup-nodes.html 
keywords: BeeGFS on NetApp, NetApp Custom Architectures, EF600 
summary: 在執行Ansible之前、手動設定檔案和區塊節點所需的步驟。 
---
= 設定檔案和區塊節點
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在執行Ansible之前、手動設定檔案和區塊節點所需的步驟。



== 檔案節點



=== 設定基礎板管理控制器（BMC）

底板管理控制器（BMC）有時稱為服務處理器、是內建於各種伺服器平台的頻外管理功能的一般名稱、即使作業系統未安裝或無法存取、也能提供遠端存取。廠商通常會以自己的品牌行銷這項功能。例如、在Lenovo SR665上、BMC稱為Lenovo XClarity Controller（XCC）。

請遵循伺服器廠商的文件、啟用存取此功能所需的任何授權、並確保BMC已連線至網路、並適當設定以供遠端存取。


NOTE: 如果需要使用RedfISH的BMC型屏障、請確認已啟用RedfISH、而且可從安裝在檔案節點上的作業系統存取BMC介面。如果BMC和營運部門共用相同的實體網路介面、則網路交換器可能需要特殊組態。



=== 調校系統設定

使用系統設定程式（BIOS / UEFI）介面、確定設定為最大化效能。確切的設定和最佳值會因使用中的伺服器機型而有所不同。提供的指南適用於link:../second-gen/beegfs-deploy-file-node-tuning.html["已驗證檔案節點機型"^]、否則請參閱伺服器廠商的文件、以及根據您的模式所提供的最佳實務做法。



=== 安裝作業系統

根據列出的文件節點要求安裝支持的操作系統link:../second-gen/beegfs-technology-requirements.html#file-node-requirements["請按這裡"^]。請根據您的Linux套裝作業系統、參閱下列任何其他步驟。



==== RedHat

使用RedHat訂購管理程式來註冊及訂閱系統、以便從正式的Red Hat儲存庫安裝所需的套件、並將更新限制在支援的Red Hat版本： `subscription-manager release --set=<MAJOR_VERSION>.<MINOR_VERSION>`。如需相關指示、請參閱 https://access.redhat.com/solutions/253273["如何註冊及訂閱RHEL系統"^] 和  https://access.redhat.com/solutions/2761031["如何限制更新"^]。

啟用包含高可用度所需套件的Red Hat儲存庫：

....
subscription-manager repo-override --repo=rhel-9-for-x86_64-highavailability-rpms --add=enabled:1
....


=== 設定管理網路

設定所需的任何網路介面、以允許在頻內管理作業系統。具體步驟取決於所使用的特定Linux發佈版本。


NOTE: 確保SSH已啟用、且所有管理介面都可從Ansible控制節點存取。



=== 更新HCA和HBA韌體

確保所有 HBA 和 HCA 均執行中列出的支援韌體版本link:https://imt.netapp.com/matrix/["NetApp 互通性對照表"^]、並視需要進行升級。有關 NVIDIA ConnectX 適配器的其他建議link:../second-gen/beegfs-technology-requirements.html#file-node-requirements["請按這裡"^]，請參見。



== 區塊節點

請依照下列步驟執行 link:https://docs.netapp.com/us-en/e-series/getting-started/getup-run-concept.html["使用E系列開始運作"^] 可在每個區塊節點控制器上設定管理連接埠、並可選擇設定每個系統的儲存陣列名稱。


NOTE: 除了確保所有區塊節點都可從可存取控制節點之外、沒有其他組態需要。其餘的系統組態將使用Ansible來套用/維護。
