---
sidebar: sidebar 
permalink: beegfs-gens.html 
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600 
summary: BeeGFS on NetApp解決方案目前正處於第二代設計階段。 
---
= 設計世代
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BeeGFS on NetApp解決方案目前正處於第二代設計階段。

第一代和第二代均採用基礎架構、整合BeeGFS檔案系統和NVMe EF600儲存系統。然而、第二代產品是以第一代產品為基礎、提供下列額外效益：

* 效能與容量加倍、同時只增加2U機架空間
* 高可用度（HA）是以共享磁碟、雙層硬體設計為基礎
* NVIDIA DGX A100超級POD外部資格




== 第二代設計

NetApp的第二代BeeGFS已經過最佳化、可滿足嚴苛工作負載的效能需求、包括高效能運算（HPC）和HPC型機器學習（ML）、深度學習（DL）和類似的人工智慧（AI）技術。透過採用共享磁碟高可用度（HA）架構、NetApp上的BeeGFS解決方案也能滿足企業和其他組織的資料耐用度和可用度需求、這些企業和組織在尋找能夠隨工作負載和使用案例而擴充的儲存設備時、無法承受停機或資料遺失的風險。此解決方案不僅已通過NetApp驗證、也已通過外部認證、成為NVIDIA DGX超級POD的儲存選項。



== 第一代設計

NetApp的第一代BeeGFS是專為使用NetApp EF600 NVMe儲存系統、BeeGFS平行檔案系統、NVIDIA DGX™A100系統及NVIDIA®Mellanox®Quantum™QM8700 200Gbps IB交換器的機器學習（ML）和人工智慧（AI）工作負載所設計。此設計也針對儲存設備和運算叢集互連架構提供200Gbps InfiniBand（IB）、為高效能工作負載提供完全以IB為基礎的架構。

如需第一代產品的詳細資訊、請參閱 link:https://www.netapp.com/pdf.html?item=/media/25445-nva-1156-design.pdf["NetApp EF系列AI搭配NVIDIA DGX A100系統和BeeGFS"^]。
